### ISSUE TITLE
Cannot add ESI key to account using quickstart

### ISSUE THREAD

**Issue by NanoPish** [OrbitalEnterprises/evekit-frontend#4]
Hey, using quickstart at the set ESI token step, I select all access rights, accept from eve sso, return to the evekit frontend, and the next is greyed out.

If I click change scopes I get a pop up where I can do nothing except cancel and then another : Failed to set ESI token, please try again. If this problem persists, please contact site admin..

Or I can click skip, but then I don't have ESI access and the software that needs it won't work.

**Comment by deadlybulb** [comment]
Hi, sorry the quickstart was not so quick!  Can you share the name you used to login to EveKit?  I see one account that looks like it attempted to set up a character named Arelia Pai several times.  Not sure if that was you.  I don't see any other attempts that look like they had trouble today.

**Comment by NanoPish** [comment]
Hey that was not me. I check evekit again and it looks okay (green). Maybe I did not wait enough, or maybe it was before I was doing it near cluster shutdown. Thanks for you quick answer.
